name: Data

on:
  schedule:
    - cron: 0 0 * * 1

  workflow_dispatch:

jobs:
  data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: api

      - uses: gradle/actions/wrapper-validation@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Run gradle
        run: ./gradlew run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit result
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(data): Update data."
          file_pattern: "*result.json"
