name: Data

on:
  schedule:
    - cron: 0 0 * * 1

  workflow_dispatch:

jobs:
  data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run gradle
        run: ./gradlew run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit result
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "feat(data): Update data."
          file_pattern: "*result.json"
